# Generated by Django 4.2 on 2025-02-25 07:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Husband',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wife', models.CharField(max_length=100)),
                ('son', models.CharField(max_length=100)),
                ('year', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
