# Generated by Django 4.2 on 2025-03-18 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='الاسم الكامل')),
                ('student_id', models.CharField(max_length=50, unique=True, verbose_name='رقم الطالب')),
                ('major', models.CharField(max_length=100, verbose_name='التخصص')),
            ],
        ),
    ]
