# Generated by Django 4.2 on 2025-03-07 10:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_drivers'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Drivers',
            new_name='Driver',
        ),
    ]
