# Generated by Django 4.2 on 2025-03-08 17:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_student'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Student',
            new_name='Student2',
        ),
    ]
