# Generated by Django 4.2 on 2025-02-24 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('win', '0002_employee2'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Employee2',
        ),
        migrations.RemoveField(
            model_name='employee',
            name='salary',
        ),
    ]
