# Generated by Django 4.2 on 2025-03-11 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=50, verbose_name='الاسم الأول')),
                ('last_name', models.CharField(max_length=50, verbose_name='الاسم الأخير')),
                ('age', models.PositiveIntegerField(verbose_name='العمر')),
                ('team', models.CharField(max_length=100, verbose_name='الفريق')),
                ('position', models.CharField(max_length=50, verbose_name='المركز')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='تاريخ الإضافة')),
            ],
            options={
                'verbose_name': 'لاعب',
                'verbose_name_plural': 'اللاعبون',
                'ordering': ['-created_at'],
            },
        ),
    ]
