# Generated by Django 4.2 on 2025-02-25 08:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='workshops',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('holle', models.CharField(max_length=100)),
                ('employees', models.CharField(max_length=100)),
                ('day', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
    ]
